package com.yo1no.gramarye.magic.runtime.mana;

enum ManaDecodeFailure {
    NULL_INPUT,
    WRONG_ROOT_TYPE,
    MISSING_SCHEMA_VERSION,
    MISSING_BALANCE,
    EXTRA_FIELD,
    WRONG_SCHEMA_VERSION_TYPE,
    WRONG_BALANCE_TYPE,
    UNSUPPORTED_SCHEMA_VERSION,
    BALANCE_BELOW_MINIMUM,
    BALANCE_ABOVE_MAXIMUM
}
