package com.yo1no.gramarye.magic.network;

enum P7IntentFailureReason {
    MALFORMED_PAYLOAD,
    PROTOCOL_VERSION_MISMATCH,
    UNAUTHENTICATED_SENDER,
    UNAUTHORIZED_INTENT,
    UNKNOWN_SKILL,
    UNKNOWN_ACTION,
    INVALID_TARGET,
    TARGET_UNAVAILABLE,
    INVALID_SEQUENCE,
    DUPLICATE_SEQUENCE,
    STALE_SEQUENCE,
    SEQUENCE_GAP,
    SEQUENCE_EXHAUSTED,
    RATE_LIMITED,
    SERVER_BUSY,
    P5_ADMISSION_REJECTED,
    P5_UNAVAILABLE,
    INTERNAL_SERVER_FAULT,
    DISCONNECTED,
    RELOAD_IN_PROGRESS
}
