package com.yo1no.gramarye;

/** Excluded compile-selected fixture; the frozen bundle fixes this value for both peers. */
final class P11C4aScenario {
    enum Mode { BASELINE, PARKING_TRANSFER, UI_CALLBACK, UI_HELD, CONFIG_RESET, C6, KEEPALIVE_WRONG, KEEPALIVE_STALE, KEEPALIVE_TIMEOUT, HOST_LEAVE, CONFIG_JOIN_CLOSE, CONFIG_ACK_CLOSE, NATIVE_SENDERS, C6_RATE_FAIRNESS, LATE_KEY, QUEUED_BENIGN, HOST_EXPIRY, PORTAL, REQUIRED_CHANNEL_MISSING, REQUIRED_VERSION_MISMATCH, MALFORMED_CONFIG_REQUEST, MALFORMED_PLAY_REQUEST, MALFORMED_CONFIG_STATE, MALFORMED_PLAY_STATE, NATIVE_CALLER_TAIL, NATIVE_FRAME_SEND, HELD_NEGATIVES, NATIVE_RAW_ERROR, NATIVE_PRIMARY_SECONDARY, PARKING_OLD_TICK, NATIVE_CONFIG_CATCH, NATIVE_REPORTED_OOME, NATIVE_SUBMISSION_REJECT, HANDOFF_STATUS, UNPAIRED_COMPLETED, CONFIG_PARKING_RESET, NATIVE_REWARD_CONTINUITY, NATIVE_CONSTRUCTOR_PRISTINE, NATIVE_CONSTRUCTOR_ESCAPED, NATIVE_COMPLETE_B_FAULT, L1_HOST_STOP, COOLDOWN_HOST }
    static final Mode MODE = "d3-c4a-baseline".equals(System.getProperty("gramarye.p11.online.case", ""))
            ? Mode.BASELINE : Mode.UI_HELD;

    private P11C4aScenario() { }

    static boolean c6() { return MODE == Mode.C6; }

    static P11C4aNativeErrorProbe.Mode nativeErrorMode() {
        return switch (MODE) {
            case NATIVE_CALLER_TAIL -> P11C4aNativeErrorProbe.Mode.CALLER_TAIL;
            case NATIVE_FRAME_SEND -> P11C4aNativeErrorProbe.Mode.FRAME_SEND;
            case NATIVE_RAW_ERROR -> P11C4aNativeErrorProbe.Mode.RAW_ERROR;
            case NATIVE_PRIMARY_SECONDARY -> P11C4aNativeErrorProbe.Mode.PRIMARY_SECONDARY;
            case NATIVE_REPORTED_OOME -> P11C4aNativeErrorProbe.Mode.REPORTED_OOME;
            case NATIVE_COMPLETE_B_FAULT -> P11C4aNativeErrorProbe.Mode.COMPLETE_B_FAULT;
            default -> null;
        };
    }
}
