package com.yo1no.gramarye.magic.definition.store;

/** Closed P4-E V0 budget vocabulary. */
enum P4E1AuditCounter {
    DIRECTORY_ENTRIES,
    RELEVANT_RECORDS,
    COMPRESSED_BYTES_PER_FILE,
    DECOMPRESSED_BYTES_PER_FILE,
    CONTAINER_DEPTH_PER_FILE,
    COMPOUND_CONTAINERS_PER_FILE,
    COMPOUND_FIELD_ENTRIES_PER_FILE,
    LIST_ELEMENTS_PER_FILE,
    BYTE_ARRAY_ELEMENTS_PER_FILE,
    INT_ARRAY_ELEMENTS_PER_FILE,
    LONG_ARRAY_ELEMENTS_PER_FILE,
    MODIFIED_UTF8_BYTES_PER_FILE,
    SCALAR_TAGS_PER_FILE,
    COMPRESSED_BYTES_TOTAL,
    DECOMPRESSED_BYTES_TOTAL,
    COMPOUND_CONTAINERS_TOTAL,
    COMPOUND_FIELD_ENTRIES_TOTAL,
    LIST_ELEMENTS_TOTAL,
    BYTE_ARRAY_ELEMENTS_TOTAL,
    INT_ARRAY_ELEMENTS_TOTAL,
    LONG_ARRAY_ELEMENTS_TOTAL,
    MODIFIED_UTF8_BYTES_TOTAL,
    SCALAR_TAGS_TOTAL,
    ATTACHMENT_ADMISSIONS,
    RAW_ROOT_CLAIMS
}
