package com.yo1no.gramarye.magic.definition.store;

/** Bounded stage vocabulary shared by P4-E1 admission checkpoints. */
enum P4E1AuditStage {
    HEAP_FLOOR_OBSERVATION,
    JOURNAL_READINESS,
    DIRECTORY_ENTRIES,
    SOURCE_SELECTION,
    RELEVANT_RECORDS,
    PER_FILE_COMPRESSED,
    AGGREGATE_COMPRESSED_CHECKED_ADD,
    GZIP_FRAMING,
    PER_FILE_DECOMPRESSED,
    AGGREGATE_DECOMPRESSED_CHECKED_ADD,
    COMPOUND_FIELD_CHECKPOINT,
    DEPTH_CONTAINER_SCALAR_KIND,
    LIST_LENGTH,
    TYPED_ARRAY_LENGTH,
    MODIFIED_UTF_PREFIX,
    DATA_VERSION,
    P4C_ADMISSION,
    ATTACHMENT_ADMISSION_COUNTER,
    RAW_ROOT_CAPTURE,
    STORE_REFERENCE_OWNER_AUDIT
}
